import type { Metadata } from "next";
import FontPopins from "./ui/fonts";
import "./globals.css";
import AuthContextProvider from "./contexts/authcontextAdmin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${FontPopins.className} antialiased`}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
