import "dotenv/config";
import type { Metadata } from "next";
import FontPopins from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${FontPopins.className} antialiased`}>{children}</body>
    </html>
  );
}
